version: '3'

services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    environment:
      - ENABLE_IPV6=true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./volumes/nginx/certs:/etc/nginx/certs:ro
      - ./volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/nginx/share:/usr/share/nginx/html
      - ./volumes/nginx/htpasswd:/etc/nginx/htpasswd
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy
